import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import User from './models/User.js';
import Post from './models/Post.js';

dotenv.config();

const seedDatabase = async () => {
  try {
    // 1. Connect to Database
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/nexusDB');
    console.log('✅ MongoDB Connected for Seeding...');

    // 2. Clear old data
    await User.deleteMany();
    await Post.deleteMany();
    console.log('🧹 Previous data cleared.');

    // 3. Hash Password (Tumhara bcrypt wala logic)
    const salt = await bcrypt.genSalt(10);
    const defaultPassword = await bcrypt.hash('Password123', salt);

    // 4. Custom NIT Srinagar Users
    const usersData = [
      {
        name: 'Vivek Kumar', username: 'vivek_kumar', email: 'vivekkr7046@gmail.com', password: defaultPassword,
        age: 21, dob: '2005-08-15', gender: 'Male',
        avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
        bio: 'NIT Srinagar ECE \'27 🎓 | Enr: 2023BECE100 | Java, Python & Web Dev 🚀'
      },
      {
        name: 'Aman Singh', username: 'aman_cse', email: 'aman@nexus.com', password: defaultPassword,
        age: 21, dob: '2005-03-10', gender: 'Male',
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
        bio: 'CSE \'27 @ NIT Srinagar | Code, Sleep, Repeat 💻'
      },
      {
        name: 'Priya Gupta', username: 'priya_it', email: 'priya@nexus.com', password: defaultPassword,
        age: 20, dob: '2006-01-22', gender: 'Female',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
        bio: 'IT \'27 NIT Sri | Frontend Developer ✨'
      },
      {
        name: 'Rahul Sharma', username: 'rahul_ece', email: 'rahul@nexus.com', password: defaultPassword,
        age: 21, dob: '2004-11-05', gender: 'Male',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
        bio: 'ECE 3rd Year | Microprocessors & Chill 🔌'
      },
      {
        name: 'Neha Reddy', username: 'neha_codes', email: 'neha@nexus.com', password: defaultPassword,
        age: 21, dob: '2005-07-18', gender: 'Female',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
        bio: 'NIT Srinagar CSE \'27 | DSA grinding everyday 😭'
      }
    ];

    const createdUsers = await User.insertMany(usersData);
    console.log(`👤 ${createdUsers.length} Users inserted!`);

    // 5. Extract Dynamic ObjectIDs generated by MongoDB
    const vivekId = createdUsers[0]._id;
    const amanId = createdUsers[1]._id;
    const priyaId = createdUsers[2]._id;
    const rahulId = createdUsers[3]._id;
    const nehaId = createdUsers[4]._id;

    // Follower-Following setup
    createdUsers[0].following = [amanId, rahulId];
    createdUsers[0].followers = [amanId, priyaId, rahulId, nehaId];
    await createdUsers[0].save();

    // 6. Custom NIT Srinagar Posts & Comments
    const postsData = [
      {
        user: amanId,
        content: 'Finally submitted the OS assignment after 3 sleepless nights. C pointer bugs are the worst! 😪 bhai koi bacha lo.',
        likes: [vivekId, rahulId, nehaId],
        comments: [{ text: 'bhai mera bhi same haal tha 😂', user: rahulId }]
      },
      {
        user: vivekId,
        content: 'Prepared a 23-slide presentation on CISC vs RISC architectures today. 8086 microprocessor is actually pretty fascinating when you understand the logic behind it! 💻🔥',
        likes: [amanId, priyaId, rahulId, nehaId],
        comments: [
          { text: 'Great job bhai! kal dikhana class me', user: amanId },
          { text: 'Mujhe bhi PPT bhej dena revise karne ke liye pls 🥲', user: priyaId }
        ]
      },
      {
        user: rahulId,
        content: 'Aharbal Waterfall trip sorted for this weekend! 🌊 Anyone else joining from Jhelum Extension hostel?',
        image: 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=800',
        likes: [vivekId, nehaId],
        comments: [
          { text: 'Me and my friends are in! 🔥 Jhelum Ext. Room JE-17 ke paas milte hain.', user: vivekId }
        ]
      },
      {
        user: priyaId,
        content: 'Stuck on Leetcode greedy algorithms again. Any good resources? YouTube tutorials are making it more confusing right now 😭',
        likes: [vivekId, nehaId],
        comments: [
          { text: 'Check out Striver\'s DSA sheet, kaafi sahi aur clear hai.', user: vivekId },
          { text: 'Same yaar, it takes so much time to build logic.', user: nehaId }
        ]
      }
    ];

    await Post.insertMany(postsData);
    console.log(`📝 Posts inserted successfully!`);

    console.log('🎉 Database Seeding Complete! Ready for Deployment 🚀');
    process.exit();
  } catch (error) {
    console.error('❌ Error during seeding:', error);
    process.exit(1);
  }
};

seedDatabase();